### ISSUE TITLE
Incorrect behaviour, if no config provided 

### ISSUE THREAD

**Issue by abelharisov** [GrahamCampbell/Laravel-Security#44]
**PHP version**: 8.0.9

**Description**
If the project doesn't have a security config, false positives are happening in some cases.
For example the string ` 'attribute1 <= 1 and attribute2 = 2'` becomes `'attribute1 <= 1 and attribute2 '`

**How to reproduce**
If the project doesn't have a security config, then a value from `vendor/graham-campbell/security/config/security.php:26` is used. A small example, which emulates this situation.

```
        $query = 'attribute1 <= 1 and attribute2 = 2';
        $security = Security::create([
            'attributes' => null,
            'tags'       => null,
        ]);
        $cleanQuery= $security->clean($query);

        var_dump(html_entity_decode($cleanQuery));  // string(31) "attribute1 <= 1 and attribute2 "
        var_dump($query === html_entity_decode($cleanQuery));  // bool(false)
```

**Comment by abelharisov** [comment]
We solved problem by adding a `config/security.php` with such content:
```
<?php

return [
    'evil' => [],
];

```

**Comment by GrahamCampbell** [comment]
I don't think this is a bug.

>   var_dump($query === html_entity_decode($cleanQuery));  // bool(false)

The purpose of this package is not to html encode the input, so I'd be concerned if this ever returned true (other than for the most basic of inputs without special characters). The idea here is to allow through html, but to remove things that may lead to XSS. This may lead to a few false positives, but this is by design. Better to have that, than to have false negatives. If there are issues with the upstream sanitizer, please report a bug with them. :)
