### ISSUE TITLE
Support for Laravel 10 

### ISSUE THREAD

**Issue by zoispag** [GrahamCampbell/Laravel-Security#46]
Hi Graham, can we get support for Laravel 10? Thanks

**Comment by GrahamCampbell** [comment]
[v11.0.0](https://github.com/GrahamCampbell/Laravel-Security/releases/tag/v11.0.0) has now been released, with Laravel 10 support. Due to some changes upstream, I had to drop Laravel 8 support, so v11 supports PHP 8.0, 8.1, 8.2 and Laravel 9 & 10. By comparison, v10 supported PHP 7.4, 8.0, 8.1 and Laravel 8 & 9.
